# Generated by Django 3.1.3 on 2020-12-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option_pricing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionsymbol',
            name='asset',
            field=models.CharField(choices=[('FTSE', 'FTSE'), ('ALPHA', 'ALPHA'), ('HTO', 'OTE'), ('ETE', 'ETE'), ('OPAP', 'OPAP'), ('PPC', 'DEH'), ('TPEIR', 'PEIRAIOS')], max_length=5),
        ),
    ]
