# Generated by Django 3.1.3 on 2020-12-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option_pricing', '0003_auto_20201202_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='change',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
